// Reads DDOBuilderV2's Effect.h, extracts the effectTypeMap[] string table,
// and emits src/types/effectTypes.ts as a TS string-literal union plus
// constant array of all known effect-type strings.
//
// The XML uses the string form (e.g. "AbilityBonus"), not the C++ enum
// identifier (e.g. "Effect_AbilityBonus"), so the map table is the
// authoritative source — not the enum itself.
//
// Run manually after pulling DDOBuilderV2 updates:
//   node scripts/genEffectTypes.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const EFFECT_H = resolve(HERE, '../../DDOBuilderV2/DDOBuilder/Effect.h');
const OUT = resolve(HERE, '../src/types/effectTypes.ts');

const src = readFileSync(EFFECT_H, 'utf8');

// Find the effectTypeMap[] block.
const start = src.indexOf('effectTypeMap[]');
if (start === -1) throw new Error('effectTypeMap[] not found in Effect.h');
const open = src.indexOf('{', start);
// The block ends with `{EffectType(0), NULL}` — find the next "};" after it.
const close = src.indexOf('};', open);
if (close === -1) throw new Error('end of effectTypeMap not found');
const block = src.slice(open + 1, close);

const entryRe = /\{\s*Effect_\w+\s*,\s*L"([^"]*)"\s*\}/g;
const names = new Set();
let m;
while ((m = entryRe.exec(block))) {
  names.add(m[1]);
}
if (names.size === 0) throw new Error('no entries parsed from effectTypeMap');

const sorted = [...names].sort();
const out = `// AUTO-GENERATED by scripts/genEffectTypes.mjs from
// DDOBuilderV2/DDOBuilder/Effect.h — do not hand-edit.
// Regenerate after pulling upstream changes.

export type EffectTypeName =
${sorted.map(n => `  | '${n}'`).join('\n')};

export const EFFECT_TYPE_NAMES: readonly EffectTypeName[] = [
${sorted.map(n => `  '${n}',`).join('\n')}
] as const;

export const KNOWN_EFFECT_TYPES = new Set<string>(EFFECT_TYPE_NAMES);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${OUT} (${sorted.length} effect types)`);
